version: '3.4'

services:
  week9:
    image: ${DOCKER_REGISTRY-}week9
    build:
      context: .
      dockerfile: Week9/Dockerfile
    ports:
      - 32775:443

  waitstaff:
    image: ${DOCKER_REGISTRY-}waitstaff
    build:
      context: .
      dockerfile: WaitStaff/Dockerfile
    ports:
      - 32776:443

  kitchen:
    image: ${DOCKER_REGISTRY-}kitchen
    build:
      context: .
      dockerfile: Kitchen/Dockerfile
    ports:
      - 32777:443

  hosts:
    image: ${DOCKER_REGISTRY-}hosts
    build:
      context: .
      dockerfile: Host-ess/Dockerfile
    ports:
      - 32778:443

  busboy:
    image: ${DOCKER_REGISTRY-}busboy
    build:
      context: .
      dockerfile: BusBoy/Dockerfile
    ports:
      - 32779:443

  bartender:
    image: ${DOCKER_REGISTRY-}bartender
    build:
      context: .
      dockerfile: Bartender/Dockerfile
    ports:
      - 32780:443
  
  rabbitconsole:
    image: ${DOCKER_REGISTRY-}rabbitconsole
    build:
      context: .
      dockerfile: RabbitConsole/Dockerfile

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq_class
#    volumes:
#      - ./rabbitmq/etc/:/etc/rabbitmq/
#      - ./rabbitmq/data/:/var/lib/rabbitmq/
#      - ./rabbitmq/logs/:/var/log/rabbitmq/
#    ports:
#      - 5672:5672
#      - 15672:15672

