version: '3.4'

services:
  busboy:
    image: ${DOCKER_REGISTRY-}busboy
    build:
      context: .
      dockerfile: BusBoy/Dockerfile
    ports:
      - 44446:443

  bartender:
    image: ${DOCKER_REGISTRY-}bartender
    build:
      context: .
      dockerfile: Bartender/Dockerfile
    ports:
      - 44445:443

  hosts:
    image: ${DOCKER_REGISTRY-}hostess
    build:
      context: .
      dockerfile: Host-ess/Dockerfile
    ports:
      - 44447:443

  kitchen:
    image: ${DOCKER_REGISTRY-}kitchen
    build:
      context: .
      dockerfile: Kitchen/Dockerfile
    ports:
      - 44448:443

  rabbitconsole:
    image: ${DOCKER_REGISTRY-}rabbitconsole
    build:
      context: .
      dockerfile: RabbitConsole/Dockerfile


  waitstaff:
    image: ${DOCKER_REGISTRY-}waitstaff
    build:
      context: .
      dockerfile: WaitStaff/Dockerfile
    ports:
      - 44449:443

  restaurantfrontend:
    image: ${DOCKER_REGISTRY-}restaurantfrontend
    build:
      context: .
      dockerfile: RestaurantFrontEnd/Dockerfile
    ports:
      - 44444:443
      
  waitstaffconsole:
    image: ${DOCKER_REGISTRY-}waitstaffconsole
    build:
      context: .
      dockerfile: WaitStaffConsole/Dockerfile
