version: '3.4'

services:
  rabbitconsole:
    image: rabbitconsole:dev
    container_name: RabbitConsole
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RabbitConsole"
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_rabbitconsole$
    volumes:
      - C:\Users\alife\Desktop\CS420Project\RabbitConsole:/app
      - C:\Users\alife\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_rabbitconsole$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_rabbitconsole$ \"/src/../../../cxb4tls/source/repos/Week9/RabbitConsole/bin/Debug/netcoreapp3.1/RabbitConsole.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  week9:
    image: week9:dev
    container_name: Week9
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Week9"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_week9$
    volumes:
      - C:\Users\alife\Desktop\CS420Project\Week9:/app
      - C:\Users\alife\Desktop\CS420Project:/src
      - C:\Users\alife\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_week9$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_week9$ \"/src/../../../cxb4tls/source/repos/Week9/Week9/bin/Debug/netcoreapp3.1/Week9.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
